### ISSUE TITLE
Could not find a version that satisfies the requirement aiohttp==3.9.1

### ISSUE THREAD

**Issue by ovjust** [OS-Copilot/OS-Copilot#11]
pip install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement aiohttp==3.9.1 (from versions: none)
ERROR: No matching distribution found for aiohttp==3.9.1

**Comment by ovjust** [comment]
Collecting uvloop==0.19.0 (from -r requirements.txt (line 123))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/9c/16/728cc5dde368e6eddb299c5aec4d10eaf25335a5af04e8c0abd68e2e9d32/uvloop-0.19.0.tar.gz (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 158.5 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]

**Comment by hccngu** [comment]
This might be an issue with the version of pip. We suggest you update pip using the following command:
`python -m pip install --upgrade pip`
Note: We have updated the code, and the structure of the code released this time is clearer and more convenient to use. Please try it again, and if you have any problems, feel free to contact us~
