### ISSUE TITLE
error when using example

### ISSUE THREAD

**Issue by 0FuzzingQ** [OS-Copilot/OS-Copilot#12]
my command is :

`python3 run.py --query "Move the text files containing the word 'agent' from the folder named 'document' to the path 'working_dir/agent'"`

get the error above:

perating System Version: Ubuntu 20.04 LTS
Task:
Your task is: Move the text files containing the word 'agent' from the folder named 'document' to the path 'working_dir/agent'
topological sort is possible
Traceback (most recent call last):
  File "run.py", line 158, in <module>
    main()
  File "run.py", line 92, in main
    code, invoke = execute_agent.generate_action(action, description, pre_tasks_info, relevant_code)
  File "/root/FRIDAY/friday/agent/friday_agent.py", line 464, in generate_action
    invoke = self.extract_information(create_msg, begin_str='<invoke>', end_str='</invoke>')[0]
IndexError: list index out of range

![Uploading 企业微信截图_465634bf-b6ff-4792-b7f0-8b05f12f61f0.png…]()

**Comment by hccngu** [comment]
We have updated the code, and the structure of the code released this time is clearer and more convenient to use. Please try it again, and if you have any problems, feel free to contact us~
