### ISSUE TITLE
Does not work with windows 

### ISSUE THREAD

**Issue by samuelwalkerAT** [OS-Copilot/OS-Copilot#13]
I encountered this error while trying to install, readme claims it runs on windows  
``` shell
 RuntimeError: uvloop does not support Windows at the moment
```
 [uvloop #536](https://github.com/MagicStack/uvloop/issues/536) its an open issue with adding windows 10 support 
@Vizonex said 

> @ystekno Unfortunately uvloop doesn't support Windows because of how Unix heavy the code is including epolls and forking (Things in which windows cannot do). But here's the good news. I'm working on another library called Winloop that uses uvloop's functionality (Almost identical) but it replaces a lot of Unix things with windows APIS. A sperate library may be necessary because I didn't want there to be compiling issues with this library. I even went as far as creating my own socketpair function. My Only Question about my project Winloop will be licensing (I'll upload the code once I have licensing settled with the library maintainers here). But beyond those concerns you'll just have to be patient. I didn't ever bring it up yet here because I didn't want to be ridiculed for my ideas.

is this something that can be added?

**Comment by walywalid** [comment]
this is meant only for macOS , for windows go to https://github.com/microsoft/UFO. 

But join the dark side and get a unix based system, or better Linux

**Comment by hccngu** [comment]
Currently, FRIDAY only supports Linux and MacOS, and we are working hard to make it run smoothly on Windows as well~
