### ISSUE TITLE
[QUESTION] how is this solution different or i should ask better than open interpreter 

### ISSUE THREAD

**Issue by HakaishinShwet** [OS-Copilot/OS-Copilot#14]
Open interpreter is great foss solution to automate task in os so my question is how is this solution better or unique in comparison with that please explain in detail if there are significant differences

**Comment by LividWo** [comment]
Hi,

Thanks for bringing Open Interpreter to our attention.
OS-Copilot differs from OI in that (1) it has a memory module, which can support (2) continued self-improving.

Open Interpreter has an excellent design in many aspects, and we are now working on learning from their code to improve OS-Copilot.

Best
