### ISSUE TITLE
[BUG]: pip install -r requirements.txt

### ISSUE THREAD

**Issue by diogodsa** [OS-Copilot/OS-Copilot#30]
The following error is occurring when running the command 'pip install -r requirements.txt'

error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\pysqlite3
      copying pysqlite3\dbapi2.py -> build\lib.win-amd64-cpython-310\pysqlite3
      copying pysqlite3\__init__.py -> build\lib.win-amd64-cpython-310\pysqlite3
      running build_ext
      Builds a C extension linking against libsqlite3 library
      building 'pysqlite3._sqlite3' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pysqlite3
  Running setup.py clean for pysqlite3
Successfully built document PyPika
Failed to build pysqlite3
ERROR: Could not build wheels for pysqlite3, which is required to install pyproject.toml-based projects

**Comment by heroding77** [comment]
You can try `pip install -e .` instead.

**Comment by diogodsa** [comment]
> You can try `pip install -e .` instead.

I tried. However, it didn't work either.

**Comment by heroding77** [comment]
> > You can try `pip install -e .` instead.
> 
> I tried. However, it didn't work either.

It seems there is an issue with your local environment. You can try running the following command first：

`pip install --force-reinstall pysqlite3
`

Then run `pip install -e .` . hope this method can solve your problem~
