### ISSUE TITLE
[BUG]: The task list obtained after planning is:[]

### ISSUE THREAD

**Issue by RufengSama** [OS-Copilot/OS-Copilot#38]
**Describe the bug**
The task list obtained after planning is:[], the list is blank and then the system exit.

the log about the issue is:
[QznaSOEze7wIgYaK] 2024-05-16 20:27:06,645 - INFO - Your task is: Move the text files containing the word 'agent' from the folder named 'document' to the path 'working_dir/agent'
[QznaSOEze7wIgYaK] 2024-05-16 20:27:07,352 - INFO - Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[QznaSOEze7wIgYaK] 2024-05-16 20:27:07,472 - ERROR - Error in planning on attempt 1: 'FridayPlanner' object has no attribute 'llm'
[QznaSOEze7wIgYaK] 2024-05-16 20:27:07,473 - ERROR - Error in planning on attempt 2: 'FridayPlanner' object has no attribute 'llm'
[QznaSOEze7wIgYaK] 2024-05-16 20:27:07,473 - ERROR - Error in planning on attempt 3: 'FridayPlanner' object has no attribute 'llm'
[QznaSOEze7wIgYaK] 2024-05-16 20:27:07,473 - ERROR - Max retries reached, planning failed.

thanks for your helping~

**Comment by heroding77** [comment]
Could you please give me more information in your log/temp0325.log?

**Comment by RufengSama** [comment]
That is the complete log information everytime I run it.
![image](https://github.com/OS-Copilot/OS-Copilot/assets/129269913/2e1b447f-2de0-4a60-8ef3-6f22a4bd5367)

MODEL_NAME="gpt-3.5"
maybe the problem is that I have to use GPT-4? I guess.

**Comment by heroding77** [comment]
Can you shown me you .env file? I guess something went wrong on it. You just need to enable the following three options in the .env file. 

![image](https://github.com/OS-Copilot/OS-Copilot/assets/52284163/f769e9a7-ce75-442f-8d5e-4e73b888949a)

By the way, you can try to use "gpt-4o-2024-05-13", which is faster and cheaper.

**Comment by RufengSama** [comment]
i have a .env file and a .env_template file.
![image](https://github.com/OS-Copilot/OS-Copilot/assets/129269913/2279a2eb-ae42-4cef-a085-dff0f430a2b0)
![image](https://github.com/OS-Copilot/OS-Copilot/assets/129269913/bc2bf89b-cac7-4302-b7e5-a8b7bd2422e5)

**Comment by heroding77** [comment]
> i have a .env file and a .env_template file. ![image](https://private-user-images.githubusercontent.com/129269913/331883390-2279a2eb-ae42-4cef-a085-dff0f430a2b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNjgzNTcsIm5iZiI6MTcxNjE2ODA1NywicGF0aCI6Ii8xMjkyNjk5MTMvMzMxODgzMzkwLTIyNzlhMmViLWFlNDItNGNlZi1hMDg1LWRmZjBmNDMwYTJiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwMTIwNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDNmZWUzYzc3M2QwZDM2Zjg2NjRhNDdlYWQ4OGE0OWI3NDc3ZmQ0ODBjMGEyNjc5ZTQwYjRiMzg0MWZkZGE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ADoczaMLKUp8vMk-uCVScm_Mu7cu0BGqcpFkvjyXLoQ) ![image](https://private-user-images.githubusercontent.com/129269913/331883420-bc2bf89b-cac7-4302-b7e5-a8b7bd2422e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNjgzNTcsIm5iZiI6MTcxNjE2ODA1NywicGF0aCI6Ii8xMjkyNjk5MTMvMzMxODgzNDIwLWJjMmJmODliLWNhYzctNDMwMi1iN2U1LWE4YjdiZDI0MjJlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwMTIwNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDNiODljYjEzYTQwMWNkMjJhZGNmMTEwOWNjOTFmMDVlNzkxNGNkZDhkZDMyNTg2ZjYwYzdhYjJlMWMzMDQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0nItsVBtJ2B-iumezfnTEieKFRsR6DrK6msiWmxEd9s)

Thank you for providing the information. Have you tried the method I mentioned? If you need a proxy, please uncomment the API_BASE_URL. And your model maybe inappropriate, please check https://openai.com/api/pricing/ for more message.

**Comment by heroding77** [comment]
> Hi, I have tried your method these days, but there are still some problems. Here is the log info and my .env file. ![image](https://private-user-images.githubusercontent.com/129269913/332076337-5cefb658-1f87-4e45-b761-471c9d7b21fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNTQ2MzgsIm5iZiI6MTcxNjI1NDMzOCwicGF0aCI6Ii8xMjkyNjk5MTMvMzMyMDc2MzM3LTVjZWZiNjU4LTFmODctNGU0NS1iNzYxLTQ3MWM5ZDdiMjFmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQwMTE4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDMyYWEyY2QxYjkzMzE4YzJmZmI2MzQ4YmFiYjRjZTBlY2Q0MTllN2ZmMTg0NTVkMzQ1ZDJlZTJjMjRhMGE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vbz7y5o5WCqRVmuKlBtzjw0RZah_yCIrLe_GJNsR5Wg) ![image](https://private-user-images.githubusercontent.com/129269913/332076560-1d4e3d86-4208-4915-9ddd-e130bde51f7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNTQ2MzgsIm5iZiI6MTcxNjI1NDMzOCwicGF0aCI6Ii8xMjkyNjk5MTMvMzMyMDc2NTYwLTFkNGUzZDg2LTQyMDgtNDkxNS05ZGRkLWUxMzBiZGU1MWY3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQwMTE4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTA5NWI4OTY1NzE0YmI5Y2I3MmE5YzhlYTE0MTc4MjViNTIxOTU5NjMwYjgwZWQ3MThiZDY4MTY3OWI4ZDhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UX8wrI3uxr44HHld_vCpuXN9hh0sE8fuljEq5K8zzy8) the API_BASE_URL i tried https://api.cpdd666.cn/v1 and that in picture. I tried gpt-4 and gpt-3.5-turbo-0125, they both work well in the test web but wrong in OS-Copilot.

![image](https://github.com/OS-Copilot/OS-Copilot/assets/52284163/fbf55094-146f-4833-9c69-05a8d5309b44)

The current issue indicates that the model selection is correct, but there is a problem with the server proxy. If you can access OpenAI without deploying a VPN, please set it up as I have. If a VPN is required, simply uncomment the API_BASE_URL.

**Comment by RufengSama** [comment]
Hi, I'm regret to tell you that my OS-Copilot is still error.
I bought a new api-key and test by 

`curl https://api.xty.app/v1/chat/completions -H "Content-Type: application/json" -H "Authorization: Bearer sk-xxx" -d '{
  "model": "gpt-4o-2024-05-13",  
  "messages": [{"role": "user", "content": "你好aaaaaa"}],
  "stream":true,
  "temperature": 0.7
}'`

I can receive data correctly.
![image](https://github.com/OS-Copilot/OS-Copilot/assets/129269913/e841c6aa-1b35-433f-9b8d-c82da1ad452a)
![image](https://github.com/OS-Copilot/OS-Copilot/assets/129269913/a71d5a0a-80be-4c56-bec7-e7045a1605a6)
![image](https://github.com/OS-Copilot/OS-Copilot/assets/129269913/2836ab9b-4554-4a53-9774-4a312ebcadb7)
![image](https://github.com/OS-Copilot/OS-Copilot/assets/129269913/8fd4f7ba-f5bb-4ad0-b044-6240576b67ef)
I tried both using WSL locally and Alibaba Cloud servers, and the situation was the same. help plz[cry cry]

**Comment by RufengSama** [comment]
I think maybe something wrong about the key!
I used an openAI official api key and connect correctly but only once.
There are still connection errors after my subsequent attempts, but I can open https://openai.com/ correctly.
How can I solve this problem. Thanks for your listening and helping!

**Comment by heroding77** [comment]
Have you ever tried to set API_BASE_URL="http://127.0.0.1:8079"?  I've seen many similar connection issues like yours being resolved in this way.
