### ISSUE TITLE
[BUG]: Not OS Independant

### ISSUE THREAD

**Issue by jjfantini** [OS-Copilot/OS-Copilot#4]
This project currently relies on `uvloop` which is only available on Mac, thus you cannot use FRIDAY on a windows machine.

**Comment by hccngu** [comment]
Sorry, currently FRIDAY only supports mac and Linux systems.

**Comment by shadowdoggie** [comment]
> Sorry, currently FRIDAY only supports mac and Linux systems.

thats a real shame. wanted to try it aswell but sadly thats not gonna happen then

**Comment by ZiruiSongBest** [comment]
Does you have any plan to support Windows?

> compatible

**Comment by LividWo** [comment]
We do. But it is not the top priority atm. Probably adding Windows support after we finish code cleaning and reorg.
